package com.example.sol_eclipsado_cm_jn.controller;

import com.example.sol_eclipsado_cm_jn.model.IWordValidator;
import com.example.sol_eclipsado_cm_jn.model.SolarEclipseGame;
import com.example.sol_eclipsado_cm_jn.model.WordValidator;
import com.example.sol_eclipsado_cm_jn.view.GameStageHolder;
import com.example.sol_eclipsado_cm_jn.view.WelcomeStageHolder;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;

import java.io.IOException;

/**
 * Controller for the welcome screen of the Solar Eclipse application.
 * It captures, validates and forwards the secret word to the game screen.
 *
 * @author Jorge Navia
 * @author Carlos Meneses
 * @version 1.3
 * @since 1.0
 */
public class WelcomeController
{
    /**
     * Main game model instance used during the welcome step.
     */
    private final SolarEclipseGame game;

    /**
     * Validator used to verify secret word rules.
     */
    private final IWordValidator wordValidator;

    /**
     * Text field where the user enters the secret word.
     */
    @FXML
    private TextField secretWordTextField;

    /**
     * Label used to display feedback messages to the user.
     */
    @FXML
    private Label feedbackLabel;

    /**
     * Creates the welcome controller and initializes required model objects.
     */
    public WelcomeController()
    {
        game = new SolarEclipseGame();
        wordValidator = new WordValidator();
    }

    /**
     * Initializes the controller after the FXML view has been loaded.
     */
    @FXML
    public void initialize()
    {
        feedbackLabel.setText("");
    }

    /**
     * Handles the start button action, validates the entered secret word,
     * stores it in the model and transitions to the game screen.
     *
     * @param event action event generated by the start button
     */
    @FXML
    public void onHandleStartButton(ActionEvent event)
    {
        String secretWord = secretWordTextField.getText();
        String validationMessage = wordValidator.getValidationErrorMessage(secretWord);

        if (!validationMessage.isEmpty())
        {
            feedbackLabel.setStyle("-fx-text-fill: #c62828;");
            feedbackLabel.setText(validationMessage);
            return;
        }

        game.setSecretWord(secretWord);

        try
        {
            GameStageHolder.getInstance().getGameController().setGame(game);
            GameStageHolder.getInstance().show();
            WelcomeStageHolder.getInstance().hide();
        }
        catch (IOException exception)
        {
            feedbackLabel.setStyle("-fx-text-fill: #c62828;");
            feedbackLabel.setText("Ocurrió un error al abrir la pantalla del juego.");
        }
    }

    /**
     * Returns the current game model associated with the welcome screen.
     *
     * @return current game model
     */
    public SolarEclipseGame getGame()
    {
        return game;
    }
}