package com.example.sol_eclipsado_cm_jn.controller;

import com.example.sol_eclipsado_cm_jn.model.SolarEclipseGame;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;

/**
 * Controller for the welcome screen of the Solar Eclipse application.
 * It handles the first interaction where the secret word is captured.
 *
 * @author Jorge Navia
 * @author Carlos Meneses
 * @version 1.1
 * @since 1.0
 */
public class WelcomeController
{
    /**
     * Main game model instance used during the welcome step.
     */
    private final SolarEclipseGame game;

    /**
     * Text field where the user enters the secret word.
     */
    @FXML
    private TextField secretWordTextField;

    /**
     * Label used to display feedback messages to the user.
     */
    @FXML
    private Label feedbackLabel;

    /**
     * Creates the welcome controller and initializes the game model.
     */
    public WelcomeController()
    {
        game = new SolarEclipseGame();
    }

    /**
     * Initializes the controller after the FXML view has been loaded.
     */
    @FXML
    public void initialize()
    {
        feedbackLabel.setText("");
    }

    /**
     * Handles the start button action and captures the entered secret word.
     *
     * @param event action event generated by the start button
     */
    @FXML
    public void onHandleStartButton(ActionEvent event)
    {
        String secretWord = secretWordTextField.getText();

        if (secretWord == null || secretWord.isBlank())
        {
            feedbackLabel.setStyle("-fx-text-fill: #c62828;");
            feedbackLabel.setText("Debes escribir una palabra antes de continuar.");
            return;
        }

        game.setSecretWord(secretWord.trim());
        feedbackLabel.setStyle("-fx-text-fill: #2e7d32;");
        feedbackLabel.setText("Palabra capturada correctamente.");
    }

    /**
     * Returns the current game model associated with the welcome screen.
     *
     * @return current game model
     */
    public SolarEclipseGame getGame()
    {
        return game;
    }
}